# Generated by Django 2.1.5 on 2019-06-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_dependente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependente',
            name='tel_fixo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tel_celular',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefone Celular'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='descricao',
            field=models.CharField(max_length=40, verbose_name='Nome'),
        ),
    ]
