# Generated by Django 2.1.5 on 2019-06-01 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20190601_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependente',
            old_name='descricao',
            new_name='nome',
        ),
    ]
